# Generated by Django 5.0.3 on 2026-06-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_abierto', models.BooleanField(default=False, verbose_name='Registro de Estudiantes Abierto (Landing/Cursos)')),
                ('pruebas_activas', models.BooleanField(default=False, verbose_name='Plataforma de Pruebas Activa (Login/Métrica)')),
            ],
            options={
                'verbose_name': 'Configuración de Plataforma',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
